INSERT INTO TB_CLIENTE (ID, NOME, ENDERECO) VALUES (100, 'JOSE SANTOS','Av 25 de Março, 200 Belém/PA'); 
INSERT INTO TB_CLIENTE (ID, NOME, ENDERECO) VALUES (200, 'MARIA JOSÉ DOS SANTOS','Tv 9 de Janeiro, 1234, Belém/PA'); 
INSERT INTO TB_CLIENTE (ID, NOME, ENDERECO) VALUES (300, 'JOSE SILVA','Rua Dr Moraes, 330 Capanema/PA'); 
INSERT INTO TB_CLIENTE (ID, NOME, ENDERECO) VALUES (400, 'PEDRO SÁ','Av 25 de Março, 200 Belém/PA'); 
INSERT INTO TB_CLIENTE (ID, NOME, ENDERECO) VALUES (500, 'KARLA MARINHO','Tv 1 de Março, 220 Belém/PA'); 